// <auto-generated />
namespace Alto_IT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Test_majVue2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Test_majVue2));
        
        string IMigrationMetadata.Id
        {
            get { return "201907030817170_Test_majVue2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
